// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKpIx2fCMtBPlPfHmiSD2t-iG541tc89w',
    appId: '1:663648290389:web:5b0f74895e6713209f36dc',
    messagingSenderId: '663648290389',
    projectId: 'fruits-hub-f76ef',
    authDomain: 'fruits-hub-f76ef.firebaseapp.com',
    storageBucket: 'fruits-hub-f76ef.firebasestorage.app',
    measurementId: 'G-E1864BXFDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZXf1BI-5zdhD979xU3FYG8mwQkhC3GPo',
    appId: '1:663648290389:android:f64f8539fe69981d9f36dc',
    messagingSenderId: '663648290389',
    projectId: 'fruits-hub-f76ef',
    storageBucket: 'fruits-hub-f76ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBydJ1d1UWvSfSUp6KhXMIe5Q77psQ72ME',
    appId: '1:663648290389:ios:97e30176523bf4319f36dc',
    messagingSenderId: '663648290389',
    projectId: 'fruits-hub-f76ef',
    storageBucket: 'fruits-hub-f76ef.firebasestorage.app',
    iosBundleId: 'com.example.fruitshup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBydJ1d1UWvSfSUp6KhXMIe5Q77psQ72ME',
    appId: '1:663648290389:ios:97e30176523bf4319f36dc',
    messagingSenderId: '663648290389',
    projectId: 'fruits-hub-f76ef',
    storageBucket: 'fruits-hub-f76ef.firebasestorage.app',
    iosBundleId: 'com.example.fruitshup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKpIx2fCMtBPlPfHmiSD2t-iG541tc89w',
    appId: '1:663648290389:web:395eb8ab753d41c29f36dc',
    messagingSenderId: '663648290389',
    projectId: 'fruits-hub-f76ef',
    authDomain: 'fruits-hub-f76ef.firebaseapp.com',
    storageBucket: 'fruits-hub-f76ef.firebasestorage.app',
    measurementId: 'G-8D85DPXFQ5',
  );
}
